# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  dockerId: 404850581@qq.com                  # 阿里云 login username
  namespace: qq79060087                             # 阿里云 命名空间
  imageName: api_template                        # 阿里云 仓库名称
  registry: registry.cn-hangzhou.aliyuncs.com   # 阿里云 公网地址
  dockerfilepath:  api_template/Dockerfile       # Github Dockerfile相对路径

steps:
- script: |
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker login --username $(dockerId) -password $(pwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: push to aliyun